#!/bin/bash

msg="Look at history for Manager, ApiKey, Message, SendgridMsg and ClearstreamMsg, etc. after this completes. (CTRL)+C"
echo "$msg"

rm ./db/migrate/*
bundle exec rails db:environment:set RAILS_ENV=development
bundle exec rails g model EventType name:string:uniq label description:text
bundle exec rails g model Source name:string:uniq details:json
bundle exec rails g model Ulog source:references event_type:references details:text
bundle exec rails g model Manager name:string:uniq public_token:string:uniq email:index
bundle exec rails g model ApiKey auth_token:token manager:references
bundle exec rails g model Team name:string:uniq name_prefix:string:uniq email:index
bundle exec rails g model Template name:string:uniq template_id sample_template_data:json
bundle exec rails g model User email:string:uniq first_name last_name preferences:json
bundle exec rails g model SendgridMsg sent_to_sendgrid:datetime mail_json:json got_response_at:datetime sendgrid_response:text read_by_user_at:datetime
bundle exec rails g model ClearstreamMsg sent_to_clearstream:datetime clearstream_response:text
# If we get more than Sendgrid and Clearstream for 3rd party messaging services, consider factoring sendgrid & clearstream => target_msg_svc
bundle exec rails g model Message sendgrid_msg:references clearstream_msg:references manager:references user:references team:references email_subject email_message:text template:references sms_message:text
# Message.sendgrid_msg_id and Message.clearstream_msg_id can be nil
sed -i 's/t.references :sendgrid_msg, null: false, foreign_key: true/t.references :sendgrid_msg, null: true, foreign_key: true/g' ./db/migrate/*_create_messages.rb
sed -i 's/t.references :clearstream_msg, null: false, foreign_key: true/t.references :clearstream_msg, null: true, foreign_key: true/g' ./db/migrate/*_create_messages.rb
# Add optional to Messages' belongs_to :sendgrid_msg and :clearstream_msg
sed -i 's/belongs_to :sendgrid_msg/belongs_to :sendgrid_msg, optional: true/g' ./app/models/message.rb
sed -i 's/belongs_to :clearstream_msg/belongs_to :clearstream_msg, optional: true/g' ./app/models/message.rb

bundle exec rake db:drop db:create db:migrate db:seed

echo ""
echo "$msg"
echo ""
