#!/bin/bash

# bundle exec rails d model ApiKey
# bundle exec rails d model Clearstream # <= ClearstreamMsg
# bundle exec rails d model EventType
# bundle exec rails d model Manager
# bundle exec rails d model Message
# bundle exec rails d model Sendgrid    # <= SendgridMsg
# bundle exec rails d model Source
# bundle exec rails d model Team
# bundle exec rails d model Template
# bundle exec rails d model User
# bundle exec rails d model Ulog

bundle exec rake db:drop db:create